import { DalleAPI } from "./generate";
import { NextPage } from 'next';

const Dalle: NextPage<{ imageUrl: string }> = ({ imageUrl }) => {
  return (
    <div>
      <h1>Image generated by DALL-E</h1>
      <img src={imageUrl} alt="DALL-E generated" />
    </div>
  );
};

export const getServerSideProps = async (context) => {
    const {prompt} = context.query;
    const apiKey = process.env.DALLE_API_KEY;
    const imageUrl = await DalleAPI(prompt, apiKey);
