import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Text, Button, Spacer, Input, Col, Row } from "@nextui-org/react";
import { useRouter } from 'next/navigation';
import { DalleAPI } from './api/images/generate';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Text
        h1
        size={120}
        css={{
          textGradient: "45deg, $blue600 -20%, $pink600 25%",
        }}
        weight="bold"
      >
        Make
      </Text>
      <Text
        h1
        size={120}
        css={{
          textGradient: "45deg, $purple600 -20%, $pink600 100%",
        }}
        weight="bold"
      >
        Presentations
      </Text>
      <Text
        h1
        em
        size={120}
        css={{
          textGradient: "45deg, $yellow600 -20%, $red600 100%",
        }}
        weight="bold"
      >
        Fast
      </Text>
      <Spacer y ={10} />
        <Button size="xl" color={"gradient"} shadow onClick={() => router.push('/mainpage')}>Get Started</Button>
      </main>
    </>
  )
}
