import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Textarea, Col, Container, Row } from "@nextui-org/react";
import { Button } from "@nextui-org/react";
import React, { useState } from 'react';
import { Text, Input, useInput, Spacer } from "@nextui-org/react";
import { MuiColorInput } from 'mui-color-input'
import Slider from '@mui/material/Slider';
type NormalColors =
  | 'default'
  | 'primary'
  | 'secondary'
  | 'success'
  | 'warning'
  | 'error';


export default function Mainpage() {
    let setstatuscolors: NormalColors = "default";
    const [color, setColor] = React.useState('#ffffff')
    const handleChange = (color) => {
        setColor(color)
      }    
    let [setstatuscolor,toSuccess] = React.useState<NormalColors>(setstatuscolors)
    let [desc, setDesc] = React.useState<string>("")
    let [keydesc, keysetDesc] = React.useState<string>("Optional")
     const {
        value: controlledValue,
        setValue: setControlledValue,
        reset,
        bindings,
      } = useInput("");
    return (

        <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <Col>
            <Container justify='center' sm>
            <Row justify='center'>
            <Text
        h1
        size={60}
        css={{
          textGradient: "45deg, $purple600 -20%, $pink600 100%",
        }}
        weight="bold"
      >
        Hello User
      </Text> 
          </Row>
          <Text h3>Title</Text>
          <Input
          clearable
          placeholder="Enter a Title"
          fullWidth = {true}
          size = "xl"
          status = {setstatuscolor}
        />
          <Spacer y = {2.5}/>
          <Text h3>Pick a color for presentation theme</Text>
          <MuiColorInput value={color} onChange={handleChange} />
          <Spacer y = {2.5}/>
          <Text h3>Select the number of Slides</Text>
          <Slider defaultValue={50} aria-label="Default" valueLabelDisplay="auto" max= {25}/>
          <Spacer y = {2.5}/>
          <Text h3>Description</Text>
          <Textarea fullWidth={true} placeholder='Enter your description'{...bindings} status = {setstatuscolor} minRows={8}
          maxRows={15} width = {"xl"} size = "xl"/>
          <Spacer y = {2.5}/>
          <Text h3>Keywords</Text>
          <Input
          clearable
          placeholder="Please enter relevant Keywords"
          fullWidth = {true}
          size = "xl"
          status = {setstatuscolor}
        />
        <Spacer y = {4}/>
        <Row justify='center'>
          <Button
                auto
                color="gradient"
                size="xl"
                shadow
                onPress={() => {
                    toSuccess(
                        setstatuscolor = "success"
                        ); 
                    setDesc(desc = "Excellent description 🚀"
                    );
                    keysetDesc(keydesc = "Great Keywords")
                }}
              > Generate Results </Button>  </Row>   
              </Container>
              </Col>  
        </main>
      </>
    )
}